Globant-UI-Engineering/Bootcamp

bogota-july-2018/calculator/andresvalderrama/calculator.js

Good night
This is my code for a basic cli calculator. It accepts only two numbers and one operand.
Thanks

creating a basic cli calculator in javascript

---

bogota-july-2018/js-calculator/LuisMiguelBarragan /assets/css/main.css
bogota-july-2018/js-calculator/LuisMiguelBarragan /calculadora.js
bogota-july-2018/js-calculator/LuisMiguelBarragan /index.html

Tarea 4: Luis Miguel Barragan

---

bogota-july-2018/html-form-a11y/jorge-aguilar_form/form.html

Activity of third day!. Form with seven inputs.

Form Activity by Jorge Aguilar

---

bogota-july-2018/html-form-a11y/AlexanderOrtiz/index.html

Alexander ortiz day3 form html

---

bogota-july-2018/cyclomatic-complexity/andresvalderrama/predict-your-age.js

Hola
Tengo una duda acerca de la complejidad ciclomática, en la ultima sentencia del kata use dos métodos del objeto Math. 
```js
return Math.floor(Math.sqrt(sumAges) / 2)
```
El uso de estos método aumentan la complejidad?
Gracias.

resolving kata, with cyclomatic complexity

---

bogota-july-2018/css-magazine-cover/LuisBarragan/css/main.css
bogota-july-2018/css-magazine-cover/LuisBarragan/css/tags.css
bogota-july-2018/css-magazine-cover/LuisBarragan/index.html

2-1: Review the Semantic and A11y in your magazine cover.

Tarea 2-1: Luis Miguel Barragán

---

bogota-july-2018/javascript-sliding-puzzle/LuisMiguelBarragan/assets/main.css
bogota-july-2018/javascript-sliding-puzzle/LuisMiguelBarragan/index.html
bogota-july-2018/javascript-sliding-puzzle/LuisMiguelBarragan/puzzle.js

Tarea 5: LuisMiguelBarragan

---

bogota-july-2018/javascript-sliding-puzzle/Juan David Ortiz/index.html
bogota-july-2018/javascript-sliding-puzzle/Juan David Ortiz/main.css
bogota-july-2018/javascript-sliding-puzzle/Juan David Ortiz/main.js

game is working properly, although UI is very basic, and scripts could be improved

Juan ortiz slide puzzle

---

bogota-july-2018/javascript-calculator/JorgeAguilar/calculator.js
bogota-july-2018/javascript-calculator/JorgeAguilar/index.html
bogota-july-2018/javascript-calculator/JorgeAguilar/style.css

Added Files to Calculator Activity

Added-Calculator Files

---

bogota-july-2018/javascript-sliding-puzzle/JorgeAguilar/assets/css/style.css
bogota-july-2018/javascript-sliding-puzzle/JorgeAguilar/assets/js/slide.js
bogota-july-2018/javascript-sliding-puzzle/JorgeAguilar/index.html

add-sliding-puzzle-files

---

bogota-july-2018/javascript-calculator/Bryan Murillo/calculadora Day5.html

<feat>[calculadoraDay5]: calculadoraDay5.html added

---

bogota-july-2018/javascript-sliding-puzzle/Cristian_Barreto/index.html
bogota-july-2018/javascript-sliding-puzzle/Cristian_Barreto/index.js
bogota-july-2018/javascript-sliding-puzzle/Cristian_Barreto/style.css

Adapted and optimised sliding puzzle from [another repo](https://github.com/danishmughal/sliding-puzzle), all credits for the original repo owner.

Feat: Add sliding puzzle homework

---

bogota-july-2018/javascript-calculator/andresvalderrama/calculator-ui.js
bogota-july-2018/javascript-calculator/andresvalderrama/calculator.css
bogota-july-2018/javascript-calculator/andresvalderrama/calculator.js
bogota-july-2018/javascript-calculator/andresvalderrama/index.html

Buenas noches
Presento tarea **calculadora** usando vanilla Javascript. Creo que aun se pueden arreglar y agregar mas cosas pero ante mi atraso en las demás tareas decidí entregar este código. :)
Gracias

Andres valderrama javascript calculator

---

bogota-july-2018/javascript-calculator/Bryan Murillo Day 6/calculadora.html
bogota-july-2018/javascript-calculator/Bryan Murillo Day 6/calculadora.js
bogota-july-2018/javascript-calculator/Bryan Murillo Day 6/style.css

Calculator UI, homework Day 6
I'm really sorry for being late with the homeworks.

Bryan murillo day6

---

bogota-abril-2019/css-magazine-cover/Nicolas-Mariño/index.html

html semantics updated

---

bogota-abril-2019/react-todo/.gitignore
bogota-abril-2019/react-todo/README.md
bogota-abril-2019/react-todo/package-lock.json
bogota-abril-2019/react-todo/package.json

To-Do list with React uploaded, waiting for review

To-Do list with React

---

bogota-abril-2019/html-form-a11y/laura_bruges-task3-WCAG_forms/index.html

Laura Brugés - Task3: WCAG HTML form

---

A11Y Form-Day3/css/index.css
A11Y Form-Day3/css/normalize.css
A11Y Form-Day3/index.html

Isis yamel a11y form day3

---

bogota-abril-2019/html-form-a11y/Juan-Ramirez/index.html

Homework finished

---

bogota-abril-2019/javascript-calculator/Sebastian-Castillo/index.html
bogota-abril-2019/javascript-calculator/Sebastian-Castillo/index.js
bogota-abril-2019/javascript-calculator/Sebastian-Castillo/style.css

✨ task-04: Add calculator for JS

Sebastian-Castillo-Task-03-Calculator

---

bogota-abril-2019/javascript-calculator/Nicolas-Mariño-Calculator/index.html
bogota-abril-2019/javascript-calculator/Nicolas-Mariño-Calculator/main.js
bogota-abril-2019/javascript-calculator/Nicolas-Mariño-Calculator/styles.css

Calculator added

---

bogota-abril-2019/javascript-calculator/Juan-David-Ramirez/app.js
bogota-abril-2019/javascript-calculator/Juan-David-Ramirez/index.html
bogota-abril-2019/javascript-calculator/Juan-David-Ramirez/style.css

This is my solution to the calculator problem using Html, Javascript and CSS.
It has the following supported operations:
- Plus.
- Substracts
- Multiplies
- Divides
- Negates
- Takes the percentage of a number in a formula
- Creates decimal numbers.
- Clears the screen
- Prints the operation result (if the operation is valid)

Calculator

---

bogota-abril-2019/javascript-sliding-puzzle/JuanDavidRamirez/app.js
bogota-abril-2019/javascript-sliding-puzzle/JuanDavidRamirez/index.html
bogota-abril-2019/javascript-sliding-puzzle/JuanDavidRamirez/style.css

Hi there! this is my sliding puzzle solution, the instructions are the following:
- Given the initial state of the game try to put all the numbers in ascendant order. 
- You can reset the state of the game if you find yourself lost
- The reason why there isn't a shuffle method on the reset button is because if i just make a random on everything there is a chance that the game is not solvable. If you want to read more about this situation check this [forum](https://math.stackexchange.com/questions/293527/how-to-check-if-a-8-puzzle-is-solvable)

Sliding Puzzle finished
